// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiRqoBWmoDGh-hzbBO-OKo4XYAP6Og5D4',
    appId: '1:695780925072:web:dab1654f26d5fbcc7f4215',
    messagingSenderId: '695780925072',
    projectId: 'ctse-project-92911',
    authDomain: 'ctse-project-92911.firebaseapp.com',
    storageBucket: 'ctse-project-92911.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9F66bbB7VecDkdFifR1fE-LrFL7U2pBA',
    appId: '1:695780925072:android:13bbf3d5904fd47d7f4215',
    messagingSenderId: '695780925072',
    projectId: 'ctse-project-92911',
    storageBucket: 'ctse-project-92911.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPJ6FBjbLHskySocZHdUyR0f7oTebj2O4',
    appId: '1:695780925072:ios:cfd078612f782be67f4215',
    messagingSenderId: '695780925072',
    projectId: 'ctse-project-92911',
    storageBucket: 'ctse-project-92911.appspot.com',
    iosClientId: '695780925072-v1ehle1hri6pnfo8ssr5bekcfokbsj7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.ctseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPJ6FBjbLHskySocZHdUyR0f7oTebj2O4',
    appId: '1:695780925072:ios:cfd078612f782be67f4215',
    messagingSenderId: '695780925072',
    projectId: 'ctse-project-92911',
    storageBucket: 'ctse-project-92911.appspot.com',
    iosClientId: '695780925072-v1ehle1hri6pnfo8ssr5bekcfokbsj7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.ctseApp',
  );
}
